program mrfantasy;
{$R *.dres}
uses
  FastMM4,
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  uPrincipal in 'modulos\00-principal\uPrincipal.pas' {fPrincipal},
  uConexaoBD in 'rotinas\uConexaoBD.pas',
  uControle in 'rotinas\uControle.pas',
  uGlobal in 'rotinas\uGlobal.pas',
  uRotinas in 'rotinas\uRotinas.pas',
  view.principal.login in 'src\view\principal\view.principal.login.pas' {frmLogin},
  uFrameAnime in 'modulos\00-principal\uFrameAnime.pas' {frm_animation: TFrame},
  view.cadastros.pesquisaPadrao in 'src\view\cadastros\view.cadastros.pesquisaPadrao.pas' {frmPesquisaPadrao},
  view.cadastros.cliente in 'src\view\cadastros\view.cadastros.cliente.pas' {frmClientes},
  uClasseCaixas in 'modulos\02-financeiro\caixas\uClasseCaixas.pas',
  uCaixas in 'modulos\02-financeiro\caixas\uCaixas.pas' {fCaixas},
  uPesquisaCaixas in 'modulos\02-financeiro\caixas\uPesquisaCaixas.pas' {fPesquisaCaixas},
  uClasseReservas in 'modulos\03-estoque\reservas\uClasseReservas.pas',
  uReservas in 'modulos\03-estoque\reservas\uReservas.pas' {fReservas},
  uPagtoReservas in 'modulos\03-estoque\reservas\uPagtoReservas.pas' {fPagtoReservas},
  uPesquisaReservas in 'modulos\03-estoque\reservas\uPesquisaReservas.pas' {fPesquisaReservas},
  uClasseVendas in 'modulos\03-estoque\vendas\uClasseVendas.pas',
  uVendas in 'modulos\03-estoque\vendas\uVendas.pas' {fVendas},
  uPagtoVendas in 'modulos\03-estoque\vendas\uPagtoVendas.pas' {fPagtoVendas},
  uPesquisaVendas in 'modulos\03-estoque\vendas\uPesquisaVendas.pas' {fPesquisaVendas},
  view.financeiro.relatorioCaixa in 'src\view\financeiro\view.financeiro.relatorioCaixa.pas' {frmReportCaixa},
  uClasseCfgWalletsDigital in 'modulos\01-cadastro\walletdigital\uClasseCfgWalletsDigital.pas',
  uCfgWalletsDigital in 'modulos\01-cadastro\walletdigital\uCfgWalletsDigital.pas' {fCfgWalletsDigital},
  uPesquisaWalletsDigital in 'modulos\01-cadastro\walletdigital\uPesquisaWalletsDigital.pas' {fPesquisaWalletsDigital},
  uClasseCartoes in 'modulos\02-financeiro\cartoes\uClasseCartoes.pas',
  uCartoes in 'modulos\02-financeiro\cartoes\uCartoes.pas' {fCartoes},
  uPesquisaCartoes in 'modulos\02-financeiro\cartoes\uPesquisaCartoes.pas' {fPesquisaCartoes},
  uPesquisaReservasProdutos in 'modulos\03-estoque\reservas\uPesquisaReservasProdutos.pas' {fPesquisaReservasProdutos},
  uImprimeComprovante in 'modulos\03-estoque\reservas\uImprimeComprovante.pas' {fImprimeComprovante},
  uConfigBackups in 'modulos\00-principal\uConfigBackups.pas' {fConfigBackups},
  uConfigImpressao in 'modulos\00-principal\uConfigImpressao.pas' {fConfigImpressao},
  uClasseOrdens in 'modulos\03-estoque\ordens\uClasseOrdens.pas',
  view.estoque.ordem in 'src\view\estoque\view.estoque.ordem.pas' {frmOrdens},
  uClasseRelatorios in 'modulos\04-relatorios\uClasseRelatorios.pas',
  uReportMovimento in 'modulos\04-relatorios\uReportMovimento.pas' {fReportMovimento},
  model.resource.interfaces in 'src\model\resource\model.resource.interfaces.pas',
  model.resource.impl.configuration in 'src\model\resource\impl\model.resource.impl.configuration.pas',
  model.resource.impl.connection.firedac in 'src\model\resource\impl\model.resource.impl.connection.firedac.pas',
  model.resource.impl.factory in 'src\model\resource\impl\model.resource.impl.factory.pas',
  model.service.interfaces in 'src\model\service\model.service.interfaces.pas',
  model.service.interfaces.impl in 'src\model\service\impl\model.service.interfaces.impl.pas',
  model.acesso in 'src\model\entity\model.acesso.pas',
  model.caixa in 'src\model\entity\model.caixa.pas',
  model.cartoes in 'src\model\entity\model.cartoes.pas',
  model.cliente in 'src\model\entity\model.cliente.pas',
  model.empresa in 'src\model\entity\model.empresa.pas',
  model.estoque in 'src\model\entity\model.estoque.pas',
  model.formasPagto in 'src\model\entity\model.formasPagto.pas',
  model.funcionario in 'src\model\entity\model.funcionario.pas',
  model.kardex in 'src\model\entity\model.kardex.pas',
  model.menu in 'src\model\entity\model.menu.pas',
  model.ordemCab in 'src\model\entity\model.ordemCab.pas',
  model.ordemItem in 'src\model\entity\model.ordemItem.pas',
  model.ordemPagto in 'src\model\entity\model.ordemPagto.pas',
  model.produto in 'src\model\entity\model.produto.pas',
  model.usuario in 'src\model\entity\model.usuario.pas',
  controller.dto.empresa.interfaces in 'src\controller\dto\controller.dto.empresa.interfaces.pas',
  controller.dto.empresa.interfaces.impl in 'src\controller\dto\impl\controller.dto.empresa.interfaces.impl.pas',
  model.carteiraDigital in 'src\model\entity\model.carteiraDigital.pas',
  view.cadastros.empresa in 'src\view\cadastros\view.cadastros.empresa.pas' {frmEmpresas},
  controller.dto.cliente.interfaces in 'src\controller\dto\controller.dto.cliente.interfaces.pas',
  controller.dto.cliente.interfaces.impl in 'src\controller\dto\impl\controller.dto.cliente.interfaces.impl.pas',
  uPesquisaPadrao in 'modulos\00-principal\uPesquisaPadrao.pas' {fPesquisaPadrao},
  view.cadastros.clientePesquisa in 'src\view\cadastros\view.cadastros.clientePesquisa.pas' {frmPesquisaClientes},
  DataSetUtils in 'rotinas\DataSetUtils.pas',
  classe.global in 'rotinas\classe.global.pas',
  controller.dto.usuario.interfaces in 'src\controller\dto\controller.dto.usuario.interfaces.pas',
  controller.dto.usuario.interfaces.impl in 'src\controller\dto\impl\controller.dto.usuario.interfaces.impl.pas',
  view.cadastros.padrao in 'src\view\cadastros\view.cadastros.padrao.pas' {frmCadPadrao},
  uLogin in 'modulos\00-principal\uLogin.pas' {fLogin},
  controller.dto.funcionario.interfaces in 'src\controller\dto\controller.dto.funcionario.interfaces.pas',
  controller.dto.funcionario.interfaces.impl in 'src\controller\dto\impl\controller.dto.funcionario.interfaces.impl.pas',
  controller.dto.produto.interfaces in 'src\controller\dto\controller.dto.produto.interfaces.pas',
  controller.dto.produto.interfaces.impl in 'src\controller\dto\impl\controller.dto.produto.interfaces.impl.pas',
  controller.dto.caixa.interfaces in 'src\controller\dto\controller.dto.caixa.interfaces.pas',
  controller.dto.caixa.interfaces.impl in 'src\controller\dto\impl\controller.dto.caixa.interfaces.impl.pas',
  controller.dto.cartoes.interfaces in 'src\controller\dto\controller.dto.cartoes.interfaces.pas',
  controller.dto.cartoes.interfaces.impl in 'src\controller\dto\impl\controller.dto.cartoes.interfaces.impl.pas',
  controller.dto.carteiraDigital.interfaces in 'src\controller\dto\controller.dto.carteiraDigital.interfaces.pas',
  controller.dto.carteiraDigital.interfaces.impl in 'src\controller\dto\impl\controller.dto.carteiraDigital.interfaces.impl.pas',
  controller.dto.ordemCab.interfaces in 'src\controller\dto\controller.dto.ordemCab.interfaces.pas',
  controller.dto.ordemCab.interfaces.impl in 'src\controller\dto\impl\controller.dto.ordemCab.interfaces.impl.pas',
  uCadPadrao in 'modulos\00-principal\uCadPadrao.pas' {fCadPadrao},
  view.cadastros.funcionario in 'src\view\cadastros\view.cadastros.funcionario.pas' {frmFuncionarios},
  view.cadastros.funcionarioPesquisa in 'src\view\cadastros\view.cadastros.funcionarioPesquisa.pas' {frmPesquisaFuncionarios},
  view.cadastros.usuario in 'src\view\cadastros\view.cadastros.usuario.pas' {frmUsuarios},
  view.cadastros.empresaPesquisa in 'src\view\cadastros\view.cadastros.empresaPesquisa.pas' {frmPesquisaEmpresas},
  model.parametro in 'src\model\entity\model.parametro.pas',
  controller.dto.parametro.interfaces in 'src\controller\dto\controller.dto.parametro.interfaces.pas',
  controller.dto.parametro.interfaces.impl in 'src\controller\dto\impl\controller.dto.parametro.interfaces.impl.pas',
  view.cadastros.usuarioPesquisa in 'src\view\cadastros\view.cadastros.usuarioPesquisa.pas' {frmPesquisaUsuarios},
  view.cadastros.produto in 'src\view\cadastros\view.cadastros.produto.pas' {frmFantasias},
  view.cadastros.produtoPesquisa in 'src\view\cadastros\view.cadastros.produtoPesquisa.pas' {frmPesquisaProdutos},
  uClasseClientes in 'modulos\01-cadastro\clientes\uClasseClientes.pas',
  uClasseEmpresas in 'modulos\01-cadastro\empresas\uClasseEmpresas.pas',
  uClasseFantasias in 'modulos\01-cadastro\fantasias\uClasseFantasias.pas',
  uClasseFuncionarios in 'modulos\01-cadastro\funcionarios\uClasseFuncionarios.pas',
  uClasseUsuarios in 'modulos\01-cadastro\usuarios\uClasseUsuarios.pas',
  view.configuracoes.carteiraDigital in 'src\view\configuracoes\view.configuracoes.carteiraDigital.pas' {frmCarteiraDigital},
  view.configuracoes.carteiraDigitalPesquisa in 'src\view\configuracoes\view.configuracoes.carteiraDigitalPesquisa.pas' {frmPesquisaCarteiraDigital},
  view.financeiro.caixa in 'src\view\financeiro\view.financeiro.caixa.pas' {frmCaixas},
  uReportCaixa in 'modulos\02-financeiro\caixas\uReportCaixa.pas' {fReportCaixa},
  view.financeiro.caixaPesquisa in 'src\view\financeiro\view.financeiro.caixaPesquisa.pas' {frmPesquisaCaixas},
  model.scripts.service.interfaces in 'src\model\service\model.scripts.service.interfaces.pas',
  model.scripts.service.interfaces.impl in 'src\model\service\impl\model.scripts.service.interfaces.impl.pas',
  view.financeiro.cartoes in 'src\view\financeiro\view.financeiro.cartoes.pas' {frmCartoes},
  view.financeiro.cartoesPesquisa in 'src\view\financeiro\view.financeiro.cartoesPesquisa.pas' {frmPesquisaCartoes},
  uOrdens in 'modulos\03-estoque\ordens\uOrdens.pas' {fOrdens},
  controller.dto.ordemItem.interfaces in 'src\controller\dto\controller.dto.ordemItem.interfaces.pas',
  controller.dto.ordemPagto.interfaces in 'src\controller\dto\controller.dto.ordemPagto.interfaces.pas',
  controller.dto.ordemItem.interfaces.impl in 'src\controller\dto\impl\controller.dto.ordemItem.interfaces.impl.pas',
  controller.dto.ordemPagto.interfaces.impl in 'src\controller\dto\impl\controller.dto.ordemPagto.interfaces.impl.pas',
  controller.dto.formaPagto.interfaces in 'src\controller\dto\controller.dto.formaPagto.interfaces.pas',
  controller.dto.formaPagto.interfaces.impl in 'src\controller\dto\impl\controller.dto.formaPagto.interfaces.impl.pas',
  controller.dto.kardex.interfaces in 'src\controller\dto\controller.dto.kardex.interfaces.pas',
  controller.dto.kardex.interfaces.impl in 'src\controller\dto\impl\controller.dto.kardex.interfaces.impl.pas',
  controller.dto.estoque.interfaces in 'src\controller\dto\controller.dto.estoque.interfaces.pas',
  controller.dto.estoque.interfaces.impl in 'src\controller\dto\impl\controller.dto.estoque.interfaces.impl.pas';

{$R *.res}
begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfPrincipal, fPrincipal);
  Application.Run;
end.
